// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwJVu5ccoRuVsbKbCe4zLU1AzWFxwi17o',
    appId: '1:616478384397:web:d4fb1419db311fa432d044',
    messagingSenderId: '616478384397',
    projectId: 'chatapp-65001',
    authDomain: 'chatapp-65001.firebaseapp.com',
    storageBucket: 'chatapp-65001.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiFqkfoS3hWd9UPu18JaHBUKWy8SurN6w',
    appId: '1:616478384397:android:2cc98e7ad2022f5a32d044',
    messagingSenderId: '616478384397',
    projectId: 'chatapp-65001',
    storageBucket: 'chatapp-65001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSNI_ghU95epILaKxxMdM7uzcgVji-H50',
    appId: '1:616478384397:ios:f02bf17726d0e74b32d044',
    messagingSenderId: '616478384397',
    projectId: 'chatapp-65001',
    storageBucket: 'chatapp-65001.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSNI_ghU95epILaKxxMdM7uzcgVji-H50',
    appId: '1:616478384397:ios:f02bf17726d0e74b32d044',
    messagingSenderId: '616478384397',
    projectId: 'chatapp-65001',
    storageBucket: 'chatapp-65001.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwJVu5ccoRuVsbKbCe4zLU1AzWFxwi17o',
    appId: '1:616478384397:web:753b7b5239445f4932d044',
    messagingSenderId: '616478384397',
    projectId: 'chatapp-65001',
    authDomain: 'chatapp-65001.firebaseapp.com',
    storageBucket: 'chatapp-65001.firebasestorage.app',
  );
}
